version: '3.1'

services:

  wordpress:
    image: stephenmiracle/frankenwp:latest
    restart: always
    ports:
      - "8095:8095" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      SERVER_NAME: ${SERVER_NAME:-:8095}
      WORDPRESS_DB_HOST: ${DB_HOST:-db}
      WORDPRESS_DB_USER: ${DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${DB_NAME:-exampledb}
      WORDPRESS_DEBUG: ${WP_DEBUG:-true}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX:-wp_}
      CADDY_GLOBAL_OPTIONS: |
        email=myemail@sample.com
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_SITEURL', 'https://dh7zotmbrk4ki.cloudfront.net');
          define('WP_HOME', 'https://dh7zotmbrk4ki.cloudfront.net');

    depends_on:
      - db
    tty: true

  db:
    image: mysql
    restart: always
    ports:
      - ${LOCAL_DB_PORT:-3309}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-exampledb}
      MYSQL_USER: ${DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    volumes:
      - dbvol:/var/lib/mysql

      
volumes:
  dbvol:
